modLoader="javafml"
loaderVersion="[47,)"
license="CC BY-NC-SA 4.0 with Modpack/Server Exception"
[[mods]]
modId="animatedinventory_validation"
version="1"
displayName="Animated Inventory Validation Fixture"
